
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/Mahmoud-Alfadel' #change it according to your repository name



# Profile information
yourname: Mahmoud Alfadel  ## put your name
title: 'master Student at KFUPM  ## your title
location: Dhahran, KSA


## Social Profiles
facebook: https://www.facebook.com/mahmood.alfadel  ## your facebook account url
twitter: https://twitter.com/mahmood_alfadel  ## your twitter account url
linkedin: https://www.linkedin.com/in/malfadel/  ## your linkedin account url




# Update all the sections by editing the files inside _includes folder.
