
title: Taher Ghaleb
url: 'http://junlulocky.com'
baseurl: '/Taher-Ghaleb' #change it according to your repository name



# Profile information
yourname: Taher Ahmed Ghaleb  ## put your name
title: 'Ph.D. Candidate at Queen&rsquo;s'  ## your title
location: Kingston, Ontario, Canada


## Social Profiles
facebook: https://www.Facebook.com/Taher.A.Ghaleb  ## my facebook account url
twitter: https://twitter.com/TaherGhaleb  ## my twitter account url
linkedin: https://www.linkedin.com/in/Taher-Ghaleb  ## my linkedin account url
googlescholar: https://scholar.google.com/citations?user=5EBfu-0AAAAJ  ## my google scholar account url
researchgate: http://www.researchgate.net/profile/Taher_Ghaleb  ## my researchgate account url



# Update all the sections by editing the files inside _includes folder.
